apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-orders
  name: ms-orders
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-orders
  template:
    metadata:
      labels:
        app: ms-orders
    spec:
      containers:
        - image: 473718918692.dkr.ecr.us-east-1.amazonaws.com/orders-service:7_test
          name: orders-service
          ports:
            - containerPort: 8080
              name: ms-orders 
              protocol: TCP
          env:
            - name: APP_ARGS
              valueFrom:
                configMapKeyRef: 
                  name: map.orders
                  key: APP_ARGS
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
# strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#   revisionHistoryLimit: 10
#   progressDeadlineSeconds: 600
#   paused: false            