apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-msord
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "*.elb.us-east-1.amazonaws.com"
    http:
      paths:
      - path: /ms-orders(/|$)(.*)
        pathType: Prefix
        backend:
          serviceName: ms-orders-svc
          servicePort: 30005
