apiVersion: v1
kind: Service
metadata:
  name: ms-orders-svc
  labels:
     app: ms-orders
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30005
    protocol: TCP
  selector:
     app: ms-orders
