apiVersion: v1
kind: Service
metadata:
  name: ms-orders-svc
  namespace: default
spec:
  spec:
  type: ClusterIP
  selector:
    app: ms-orders
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: default
